/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#121316",
        "surface-dim": "#121316",
        "surface-bright": "#38393c",
        "surface-container-lowest": "#0d0e11",
        "surface-container-low": "#1b1b1f",
        "surface-container": "#1f1f23",
        "surface-container-high": "#292a2d",
        "surface-container-highest": "#343538",
        "surface-variant": "#343538",
        surface: "#121316",
        "surface-border": "#262930",
        "on-surface": "#e3e2e6",
        "on-surface-variant": "#ccc7ab",
        "inverse-surface": "#e3e2e6",
        "inverse-on-surface": "#2f3034",
        outline: "#959177",
        "outline-variant": "#4a4732",
        "surface-tint": "#d5cb00",
        primary: {
          DEFAULT: "#ffffff",
          50: "#eff6ff",
          100: "#dbeafe",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
        },
        "on-primary": "#353200",
        "primary-container": "#f3e700",
        "on-primary-container": "#6c6700",
        "primary-fixed": "#f3e700",
        "primary-fixed-dim": "#d5cb00",
        "on-primary-fixed": "#1e1c00",
        "on-primary-fixed-variant": "#4c4800",
        secondary: "#d0bcff",
        "on-secondary": "#3c0091",
        "secondary-container": "#571bc1",
        "on-secondary-container": "#c4abff",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#23005c",
        "on-secondary-fixed-variant": "#5516be",
        tertiary: "#ffffff",
        "on-tertiary": "#003824",
        "tertiary-container": "#6ffbbe",
        "on-tertiary-container": "#00734e",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.375rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "margin-desktop": "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "code-block": ["JetBrains Mono", "monospace"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "code-inline": ["JetBrains Mono", "monospace"],
        "kbd-shortcut": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["0.875rem", { lineHeight: "1.375rem", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-sm": ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.025em", fontWeight: "600" }],
        "code-block": ["0.75rem", { lineHeight: "1.35rem", letterSpacing: "0em", fontWeight: "400" }],
        "label-mono": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["0.9375rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "code-inline": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "kbd-shortcut": ["0.625rem", { lineHeight: "0.75rem", letterSpacing: "0.04em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

